# Generated by Django 5.0.3 on 2024-03-26 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(help_text='Enter field documentation', max_length=20)),
                ('LastName', models.CharField(help_text='Enter field doccumentation', max_length=20)),
                ('Email', models.EmailField(help_text='Enter Field Documentation', max_length=254)),
                ('Message', models.CharField(help_text='Enter field doccumentation', max_length=112)),
            ],
        ),
    ]
