# Generated by Django 5.0.3 on 2024-03-26 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_blogs_alter_contact_email_alter_contact_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='BlogContent',
            field=models.TextField(),
        ),
    ]
